package learnSE.exception;

// 这是一个受查异常
public class TestSecondException extends Exception{
}
